### ISSUE TITLE
Doubt in ordering, missing, and correlation class of errors

### ISSUE THREAD

**Issue by SankBad** [ConfigV/ConfigV#6]
Hi @santolucito,

This is great work and I am working on a similar problem. 
 I have doubts in some of these techniques.

Ordering: Most of the time users edit existing files. While doing so users might change the value and do not change the order. Let's say we have two keywords key_a and key_b. These two keys are independent. But in most of these files have key_a before key_b. Hence, we might learn the wrong rule. 

Correlation: Similarly, let's say we two independent keys key_a and key_b. The value of key_a is always in 100mbs and key_b in 100kbs. So our created rules is key_a> key_b. but this is wrong rule because key_a and key_b are independent. 

Similarly, we can explain this situation for missing keyword class of errors.

**Comment by santolucito** [comment]
Hi @SankBad 

The "rules" we learn with ConfigV are based on frequency, and there are times when frequency does imply a true "rule". Your concerns are valid, and indeed, using only the association rule learning idea, we find a number of "false positive" rules. 

In order to filter out some of these incorrect rules, we use techniques such as probabilistic typing and hypergraph ordering, as described in https://dl.acm.org/doi/10.1145/3133888

At the end of the day, ConfigV is learning specifications that are only probabilistically correct. Some of these rules are issues with correctness, performance, but some times the frequency only implies convention (eg the issue with copy and pasting code and the resultant ordering rules). Whether or not rules learned from convention should be included probably depends on the goals of the application.

**Comment by SankBad** [comment]
Thanks, @santolucito. 
I was worried about false positives. 
I already read your paper and its awesome. Indeed, the probabilistic datatype approach reduces false positives rules.
but as you said,  but some times the frequency only implies convention, and it's unavoidable. 

Thanks again!

**Comment by santolucito** [comment]
best of luck on your work - hope to hear more about it soon!
